/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAlimentosRouteImport } from './routes/_site.alimentos'
import { Route as SiteCriancasRouteImport } from './routes/_site.criancas'
import { Route as SiteInformeSeRouteImport } from './routes/_site.informe-se'
import { Route as SiteJogoRouteImport } from './routes/_site.jogo'
import { Route as SiteManualRouteImport } from './routes/_site.manual'
import { Route as SiteMeuDiaRouteImport } from './routes/_site.meu-dia'
import { Route as SiteMeuPerfilRouteImport } from './routes/_site.meu-perfil'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAlimentosRoute = SiteAlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCriancasRoute = SiteCriancasRouteImport.update({
  id: '/criancas',
  path: '/criancas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInformeSeRoute = SiteInformeSeRouteImport.update({
  id: '/informe-se',
  path: '/informe-se',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJogoRoute = SiteJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteManualRoute = SiteManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMeuDiaRoute = SiteMeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMeuPerfilRoute = SiteMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/alimentos': typeof SiteAlimentosRoute
  '/criancas': typeof SiteCriancasRoute
  '/informe-se': typeof SiteInformeSeRoute
  '/jogo': typeof SiteJogoRoute
  '/manual': typeof SiteManualRoute
  '/meu-dia': typeof SiteMeuDiaRoute
  '/meu-perfil': typeof SiteMeuPerfilRoute
}
export interface FileRoutesByTo {
  '/alimentos': typeof SiteAlimentosRoute
  '/criancas': typeof SiteCriancasRoute
  '/informe-se': typeof SiteInformeSeRoute
  '/jogo': typeof SiteJogoRoute
  '/manual': typeof SiteManualRoute
  '/meu-dia': typeof SiteMeuDiaRoute
  '/meu-perfil': typeof SiteMeuPerfilRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/alimentos': typeof SiteAlimentosRoute
  '/_site/criancas': typeof SiteCriancasRoute
  '/_site/informe-se': typeof SiteInformeSeRoute
  '/_site/jogo': typeof SiteJogoRoute
  '/_site/manual': typeof SiteManualRoute
  '/_site/meu-dia': typeof SiteMeuDiaRoute
  '/_site/meu-perfil': typeof SiteMeuPerfilRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alimentos'
    | '/criancas'
    | '/informe-se'
    | '/jogo'
    | '/manual'
    | '/meu-dia'
    | '/meu-perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alimentos'
    | '/criancas'
    | '/informe-se'
    | '/jogo'
    | '/manual'
    | '/meu-dia'
    | '/meu-perfil'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/alimentos'
    | '/_site/criancas'
    | '/_site/informe-se'
    | '/_site/jogo'
    | '/_site/manual'
    | '/_site/meu-dia'
    | '/_site/meu-perfil'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/alimentos': {
      id: '/_site/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof SiteAlimentosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/criancas': {
      id: '/_site/criancas'
      path: '/criancas'
      fullPath: '/criancas'
      preLoaderRoute: typeof SiteCriancasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/informe-se': {
      id: '/_site/informe-se'
      path: '/informe-se'
      fullPath: '/informe-se'
      preLoaderRoute: typeof SiteInformeSeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/jogo': {
      id: '/_site/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof SiteJogoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/manual': {
      id: '/_site/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof SiteManualRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/meu-dia': {
      id: '/_site/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof SiteMeuDiaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/meu-perfil': {
      id: '/_site/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof SiteMeuPerfilRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAlimentosRoute: typeof SiteAlimentosRoute
  SiteCriancasRoute: typeof SiteCriancasRoute
  SiteInformeSeRoute: typeof SiteInformeSeRoute
  SiteJogoRoute: typeof SiteJogoRoute
  SiteManualRoute: typeof SiteManualRoute
  SiteMeuDiaRoute: typeof SiteMeuDiaRoute
  SiteMeuPerfilRoute: typeof SiteMeuPerfilRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAlimentosRoute: SiteAlimentosRoute,
  SiteCriancasRoute: SiteCriancasRoute,
  SiteInformeSeRoute: SiteInformeSeRoute,
  SiteJogoRoute: SiteJogoRoute,
  SiteManualRoute: SiteManualRoute,
  SiteMeuDiaRoute: SiteMeuDiaRoute,
  SiteMeuPerfilRoute: SiteMeuPerfilRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
