/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteJogoRouteImport } from './routes/_site.jogo'
import { Route as SiteInformeSeRouteImport } from './routes/_site.informe-se'
import { Route as SiteAlimentosRouteImport } from './routes/_site.alimentos'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJogoRoute = SiteJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInformeSeRoute = SiteInformeSeRouteImport.update({
  id: '/informe-se',
  path: '/informe-se',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAlimentosRoute = SiteAlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/alimentos': typeof SiteAlimentosRoute
  '/informe-se': typeof SiteInformeSeRoute
  '/jogo': typeof SiteJogoRoute
}
export interface FileRoutesByTo {
  '/alimentos': typeof SiteAlimentosRoute
  '/informe-se': typeof SiteInformeSeRoute
  '/jogo': typeof SiteJogoRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/alimentos': typeof SiteAlimentosRoute
  '/_site/informe-se': typeof SiteInformeSeRoute
  '/_site/jogo': typeof SiteJogoRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alimentos' | '/informe-se' | '/jogo'
  fileRoutesByTo: FileRoutesByTo
  to: '/alimentos' | '/informe-se' | '/jogo' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/alimentos'
    | '/_site/informe-se'
    | '/_site/jogo'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/jogo': {
      id: '/_site/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof SiteJogoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/informe-se': {
      id: '/_site/informe-se'
      path: '/informe-se'
      fullPath: '/informe-se'
      preLoaderRoute: typeof SiteInformeSeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/alimentos': {
      id: '/_site/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof SiteAlimentosRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAlimentosRoute: typeof SiteAlimentosRoute
  SiteInformeSeRoute: typeof SiteInformeSeRoute
  SiteJogoRoute: typeof SiteJogoRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAlimentosRoute: SiteAlimentosRoute,
  SiteInformeSeRoute: SiteInformeSeRoute,
  SiteJogoRoute: SiteJogoRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
